project:
  type: website
  output-dir: docs
  resources:
    - /slides
    - /readings/"*.pdf"

website:
  page-navigation: true
  title: "INFO 523"
  description: "Homepage for INFO 523 - Data Mining and Discovery at The University of Arizona, Spring 2024."
  favicon: /images/logo.png

  repo-url: https://github.com/INFO523-S24/INFO523-S24
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#EF4056" # AZ Red
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/INFO523-S24
        text: "GitHub organization"
      - icon: code-square
        href: https://jupyter.org/try
        text: "Jupyter Lab"
      - icon: person-fill
        href: https://d2l.arizona.edu/d2l/home/1396832
        text: "D2L"
        menu:
          - text: Announcements
            href: https://datamineaz-spring2024.slack.com
          - text: Zoom meetings
            href: https://arizona.zoom.us/my/gregchism
          - text: Gradebook
            href: https://d2l.arizona.edu/d2l/home/1396832

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
          - href: tables/model-cheatsheet.qmd
            text: Model cheatsheet table
      - section: "Computing"
        contents:
          - href: computing/computing-troubleshooting.qmd
            text: Troubleshooting
          - href: computing/computing-cheatsheets.qmd
            text: Cheatsheets
          - href: computing/computing-git.qmd
            text: Setting up Git
      - section: "Projects"
        contents: 
          - href: project/project-1.qmd
            text: Project 1
          - href: project/project-2.qmd
            text: Project 2
      - section: "Homework"
        contents:
          - href: homework/hw-01.qmd
            text: HW 01
          - href: homework/hw-02.qmd
            text: HW 02
          - href: homework/hw-03.qmd
            text: HW 03
          #- href: homework/hw-04.qmd
            #text: HW 04
          #- href: homework/hw-05.qmd
            #text: HW 05
          #- href: homework/hw-06.qmd
            #text: HW 06
      #- section: "Student work"
      - section: Exercises
        contents:
          - href: exercises/ex-06.qmd
          #- href: exercises/ex-08.qmd
          #- href: exercises/ex-09.qmd
          #- href: exercises/ex-12.qmd

            
  page-footer:
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
    left: "© Copyright 2023-2024, Greg Chism"
    background: "#AB0520" # AZ Red

format:
  html:
    theme:
      light: [cosmo, style/info526.scss]
      dark: [cosmo, style/info526.scss, style/dark.scss]
    linkcolor: "#EF4056" # Azurite
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Montserrat"

execute:
  freeze: auto

editor: visual
